### ISSUE TITLE
Add Switch

### ISSUE THREAD

**Issue by CryptonymAMS** [wa008/PopTranslate#4]
Hello ,hope to add a switch, similar to Tampermonkey's plug-in switch. In most cases, I don’t need to use translation tools. For example, when reading content in my native language, I don’t want a pop-up window to appear when selecting text.

**Comment by wa008** [comment]
Thanks for your feedback!

Actually, the translation window doesn’t pop if you are reading native language (source language is equal with target language except a little accidents like special symbols, which will be fixed in next version), can you provide some unexpected example? Like websites, seleted words and your target language.

Or is there other situations where you don’t want the translation window display? Which can help me to know the priority of this function.

**Comment by CryptonymAMS** [comment]
Hi,I just tried to reproduce the anomaly,but it failed.The website is [this one](https://github.com/ruanyf/weekly/blob/master/docs/issue-318.md), where I found  your excellent work ; ) ,and as you can see my target language is Chinese.

The first situation : I wanted to read a paper in English independently, without relying on translation, as a way to practice my poor English skills.
The second one : I need to use the web to show some content to the public or partners, which is not in Chinese, sometimes I select some sentences to emphasize, at this time there can be no additional pop-ups to distract them.

There are a lot of complex scenarios, and it may be impossible to adapt to all the requirements by automatically identifying whether to pop-up, so I expect to add a switch that is more convenient to operate, and it is up to the user to decide whether to close the pop-up window, after all， the switch entrance of the Google plug-in is too deep.

**Comment by wa008** [comment]
> Hi,I just tried to reproduce the anomaly,but it failed.The website is [this one](https://github.com/ruanyf/weekly/blob/master/docs/issue-318.md), where I found your excellent work ; ) ,and as you can see my target language is Chinese.
> 
> The first situation : I wanted to read a paper in English independently, without relying on translation, as a way to practice my poor English skills. The second one : I need to use the web to show some content to the public or partners, which is not in Chinese, sometimes I select some sentences to emphasize, at this time there can be no additional pop-ups to distract them.
> 
> There are a lot of complex scenarios, and it may be impossible to adapt to all the requirements by automatically identifying whether to pop-up, so I expect to add a switch that is more convenient to operate, and it is up to the user to decide whether to close the pop-up window, after all， the switch entrance of the Google plug-in is too deep.

Thanks for your feedback! I have similar problems when I use github. I will try to realise this function recently.

**Comment by wa008** [comment]
I have already built this feature in version 2.0 and published it to Chrome developer Store, it generally spent 1-3 days to review.

**Comment by wa008** [comment]
PopTranslate 2.0 published successful in chrome extension store, you can try it.
Feel free to submit feedback if you have more questions, hope you enjoy.

**Comment by CryptonymAMS** [comment]
Thx，it's perfect,nice job ; )
